name: Deploy Jekyll Blog to stellar2703.github.io/pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "/pages"
        env:
          JEKYLL_ENV: production
          
      - name: Deploy to stellar2703.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: Stellar2703/stellar2703.github.io
          publish_branch: main
          publish_dir: ./_site
          destination_dir: pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Jekyll blog to pages subdirectory'